<header>
    <div class="col-xs-12 remove-padding push-20-top">
        <div class="col-md-1">
            <a href="<?php echo PAYCORES_HOST_NAME ?>principal/activeForce">
                <button class="btn-outline">Fuerzas</button>
            </a>
        </div>
        <div class="col-md-11">
            <?php
            echo $this->tag->form(
                array(
                    "action" => "principal", "method" => "post", "id" => "form"
                )
            ); ?>
            <div class="col-md-1">
                <input type="text" class="input-ge" name="idAdmin" id="idFilter" placeholder="Id fuerza"/>
            </div>
            <div class="col-md-2">
                <input type="text" class="input-ge" name="name" id="nameFilter" placeholder="Nombre"/>
            </div>
            <div class="col-md-2">
                <input type="text" class="input-ge" name="city" id="cityFilter" placeholder="Ciudad"/>
            </div>
            <div class="col-md-2">
                <input type="text" class="input-ge" name="phone" id="phoneFilter" placeholder="Telefono"/>
            </div>
            <div class="col-md-2">
                <input type="text" class="input-ge" name="email" id="emailFilter" placeholder="Correo"/>
            </div>
            <div class="col-md-2">
                <input type="text" class="input-ge" name="ocupation" id="ocupationFilter" placeholder="ocupation value"/>
            </div>
            <div class="col-md-1 center">
                <button type="submit" class="btn-outline rounded"> compilar datos</button>
            </div>
            </form>
        </div>
    </div>
</header>

<?php if (isset($allDataForce)) { ?>
    <?php if (count($allDataForce) > 0) { ?>
        <div class="col-lg-5 col-xs-12 remove-padding push-50-top text-white text-shadow push-40-left overflow-scroll"
             style="height: 800px;">
            <?php for ($i = 0;
                       $i < count($allDataForce);
                       $i++) {
                if ($allDataForce[$i]['ocupation'] == 'AMBULANCIA') {
                    $icon = 'fa fa-ambulance';
                }
                else if ($allDataForce[$i]['ocupation'] == 'EJERCITO') {
                    $icon = 'fa fa-fighter-jet';
                }
                else if ($allDataForce[$i]['ocupation'] == 'POLICIA') {
                    $icon = 'fa fa-cab';
                }
                else if ($allDataForce[$i]['ocupation'] == 'BOMBEROS') {
                    $icon = 'glyphicon glyphicon-fire';
                }
                else if ($allDataForce[$i]['ocupation'] == 'DEFENSA CIVIL') {
                    $icon = 'fa fa-institution';
                }
                else if ($allDataForce[$i]['ocupation'] == 'FISCALIA') {
                    $icon = 'fa fa-balance-scale';
                }
                else if ($allDataForce[$i]['ocupation'] == 'TRANSITO') {
                    $icon = 'fa fa-car';
                }
                else if ($allDataForce[$i]['ocupation'] == 'CRUZ ROJA') {
                    $icon = 'fa fa-plus';
                }
                else {
                    $icon = 'fa fa-user';
                } ?>
                <div class="col-xs-12 push-20-top">
                    <div class="absolute opacity-5 bg-black shadow-4 col-xs-11 heightx100"></div>
                    <div class="col-md-2 push-20-top font-s36 padding-15 center">
                        <span class="fa <?= $icon ?> push-15-left"></span>
                        <?php
                        echo $this->tag->form(
                            array(
                                "action" => "principal/deleteAdmin", "method" => "post", "id" => "form", "class" => "absolute font-s12 pull-30-top"
                            )
                        ); ?>
                        <input type="hidden" class="form-control" name="id_admin" id="id_admin"
                               value="<?php echo $allDataForce[$i]['id_admin']; ?>"/>
                        <button type="submit" class="btn btn-danger rounded opacity-5"><span
                                class="fa fa-remove"></span></button>
                        </form>
                    </div>
                    <div class="col-md-10 push-20-top padding-20-b">
                        <div class="col-xs-12">
                            <div class="col-md-1">
                                <p><?php echo $allDataForce[$i]['id_admin']; ?></p>
                            </div>
                            <div class="col-md-5">
                                <p><?php echo $allDataForce[$i]['fullName']; ?></p>
                            </div>
                            <div class="col-md-6">
                                <p><?php echo $allDataForce[$i]['email']; ?></p>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="col-md-3">
                                <p><?php echo $allDataForce[$i]['phone']; ?></p>
                            </div>
                            <div class="col-md-3">
                                <p><?php echo $allDataForce[$i]['placa']; ?></p>
                            </div>
                            <div class="col-md-3">
                                <p><?php echo $allDataForce[$i]['city']; ?></p>
                            </div>
                            <div class="col-md-3 remove-padding">
                                <button class="btn btn-primary rounded btn-sm" onclick="initMap(<?=$allDataForce[$i]['location'];?>)">Ver ubicación</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php }; ?>
        </div>
    <?php } ?>
<?php } ?>

<div class="pull-right resplandor-ge push-50-top" id="div-map">
    <div id="map" class="pull-right col-xs-12 wow zoomIn"></div>
</div>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApG5XlUDnYYXi4pKkv2_ucfx_kZZqAaWw&callback=initMap">
</script>
<script>
    var listenmarkers = [];
    function initMap(location_admin_1, location_admin_2) {
        if(location_admin_1){

            var latLng = {lat: location_admin_1, lng: location_admin_2};

            var map = new google.maps.Map(document.getElementById('map'), {
                zoom:15, center: latLng,
                styles: [
                    {
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#212121"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.icon",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.text.stroke",
                        "stylers": [
                            {
                                "color": "#212121"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.country",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#9e9e9e"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.land_parcel",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.locality",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#bdbdbd"
                            }
                        ]
                    },
                    {
                        "featureType": "poi",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#181818"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#616161"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "labels.text.stroke",
                        "stylers": [
                            {
                                "color": "#1b1b1b"
                            }
                        ]
                    },
                    {
                        "featureType": "road",
                        "elementType": "geometry.fill",
                        "stylers": [
                            {
                                "color": "#2c2c2c"
                            }
                        ]
                    },
                    {
                        "featureType": "road",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#8a8a8a"
                            }
                        ]
                    },
                    {
                        "featureType": "road.arterial",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#373737"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#3c3c3c"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway.controlled_access",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#4e4e4e"
                            }
                        ]
                    },
                    {
                        "featureType": "road.local",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#616161"
                            }
                        ]
                    },
                    {
                        "featureType": "transit",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "water",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#000000"
                            }
                        ]
                    },
                    {
                        "featureType": "water",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#3d3d3d"
                            }
                        ]
                    }
                ],
                fullscreenControl: true,
                streetViewControl: true,
                mapTypeControl: true,
                fullscreenControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                },
                streetViewControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                },
                mapTypeControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                }
            });

            var marker = new google.maps.Marker({
                position: latLng,
                map: map,
                visible: true,
                clickable: true,
                animation: google.maps.Animation.DROP
            });
        }
        else{
            var uluru = {lat: 4.531702, lng: -75.674658};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom:14, center: {
                    lat: 4.531702, lng: -75.674658
                },
                styles: [
                    {
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#212121"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.icon",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "elementType": "labels.text.stroke",
                        "stylers": [
                            {
                                "color": "#212121"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.country",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#9e9e9e"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.land_parcel",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "administrative.locality",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#bdbdbd"
                            }
                        ]
                    },
                    {
                        "featureType": "poi",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#181818"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#616161"
                            }
                        ]
                    },
                    {
                        "featureType": "poi.park",
                        "elementType": "labels.text.stroke",
                        "stylers": [
                            {
                                "color": "#1b1b1b"
                            }
                        ]
                    },
                    {
                        "featureType": "road",
                        "elementType": "geometry.fill",
                        "stylers": [
                            {
                                "color": "#2c2c2c"
                            }
                        ]
                    },
                    {
                        "featureType": "road",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#8a8a8a"
                            }
                        ]
                    },
                    {
                        "featureType": "road.arterial",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#373737"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#3c3c3c"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway.controlled_access",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#4e4e4e"
                            }
                        ]
                    },
                    {
                        "featureType": "road.local",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#616161"
                            }
                        ]
                    },
                    {
                        "featureType": "transit",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#757575"
                            }
                        ]
                    },
                    {
                        "featureType": "water",
                        "elementType": "geometry",
                        "stylers": [
                            {
                                "color": "#000000"
                            }
                        ]
                    },
                    {
                        "featureType": "water",
                        "elementType": "labels.text.fill",
                        "stylers": [
                            {
                                "color": "#3d3d3d"
                            }
                        ]
                    }
                ],
                fullscreenControl: true,
                streetViewControl: true,
                mapTypeControl: true,
                fullscreenControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                },
                streetViewControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                },
                mapTypeControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER
                }
            });
            var data = {
                'active': 3
            };
            $.ajax({
                url: '<?=PAYCORES_HOST_NAME?>principal/principal',
                type: 'POST',
                data: data,
                success: function (response) {
                    obj = JSON.parse(response);
                    console.log(obj.status);
                    if (obj.status) {
                        var data = obj.data;
                        console.log(data);
                        for (var i = 0; i < data.length; i++) {
                            console.log(data[i]['fullName']);
                            console.log(data[i]['location']);

                            var location = data[i]['location'].split(",");
                            console.log(location[0]);
                            console.log(location[1]);

                            if(data[i]['ocupation'] === 'AMBULANCIA'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_ambulance.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === 'BOMBEROS'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_bomberos.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === 'DEFENSA CIVIL'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_defensa_civil.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === ''){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_fiscalia.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === ''){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_transito.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === 'CRUZ ROJA'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_cruz_roja.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === 'POLICIA'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_cruz_roja.png', origin: new google.maps.Point(0, 0) };
                            }
                            else if(data[i]['ocupation'] === 'EJERCITO'){
                                var image = { url: '<?= PAYCORES_HOST_NAME ?>img/marker_force.png', origin: new google.maps.Point(0, 0) };
                            }
                            var latLng = new google.maps.LatLng(location[0], location[1]);

                            var marker = new google.maps.Marker({
                                position: latLng,
                                map: map,
                                visible: true,
                                icon: image,
                                clickable: true,
                                animation: google.maps.Animation.DROP
                            });

                        }
                    }

                }
            });
        }
    }
</script>