<style>


    body {
        background-color: #6C7A89;
        font-family: sans-serif;
    }

    .node {
        stroke: #666;
        stroke-width: 1.5px;
        cursor: pointer;
    }

    .link {
        stroke: #999;
        stroke-opacity: .6;
    }

    svg {
        box-shadow: 4px 4px 10px rgba(30, 30, 30, 0.7);
        position: relative;
        left: 50%;
        margin-left: -400px;
    }

    #graph {
        padding-top: 30px;
    }

    #tooltip {
        position: absolute;
        background-color: #222;
        color: #f6f6f6;
        padding: 8px;
        border-radius: 5px;
        pointer-events: none;
        text-align: center;
        opacity: 0;
    }

    p {
        padding: 2px ;
    }

    text.legend {
        fill: #222;
        font-size: 14px;
    }

    image {
        z-index: 10;
    }

</style>
<div id="graph"></div>
<div id="tooltip">
    <p id="name"></p>
    <p id="count"></p>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script type="text/javascript" src="<?=PAYCORES_HOST_NAME?>js/main.js">


</script>