<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->


        <title>GE-911 Panel</title>


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="shortcut icon" href="<?php echo $this->url->get('favicon.ico'); ?>" type="image/x-icon">
        <link rel="icon" href="<?php echo $this->url->get('favicon.ico'); ?>" type="image/x-icon">
        <link rel="stylesheet" href="<?php echo $this->url->get('css/ultralence.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->url->get('css/animations.css'); ?>">
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <style>
            .bg-ge, body {
                background: url(http://jarvis.ai-dot.net/images/1.jpg) center center / cover no-repeat fixed;
            }
        </style>
        <!-- Animate.css es una dependencia requerida por WOW.js -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

        <!-- WOW.js library -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    </head>
    <body >
            <?php echo $this->getContent(); ?>
            <!-- Latest compiled and minified JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

            <script src="<?php echo $this->url->get('js/animations.js'); ?>"></script>
            <script src="<?php echo $this->url->get('js/ultralence.js'); ?>"></script>
            <script>new WOW().init();</script>
    </body>
</html>


